source 'https://rubygems.org'
 
# You may use http://rbenv.org/ or https://rvm.io/ to install and use this version
ruby ">= 2.7.0"
 
gem 'cocoapods', '>= 1.13'
gem 'activesupport', '>= 7.2.3.1', '< 8.0'

# Ruby 3.4.0 has removed some libraries from the standard library.
gem 'bigdecimal'
gem 'logger'
gem 'benchmark'
gem 'mutex_m'
gem 'nkf'
